### ISSUE TITLE
Allow custom value for empty value

### ISSUE THREAD

**Issue by johnjohndoe** [dirkschumacher/blume_messnet_api#5]
When I export data from the API some cells do **not contain sensor values** as shown as red cells in the screenshot.

![64ddc728-3778-11e5-8c6a-20516240e10d](https://cloud.githubusercontent.com/assets/144518/9625334/9818a2ce-5155-11e5-8b1e-d351b44f63e1.png)

 I would like to be able to configure the API so that all **empty values** are replaced with a **custom number** such as `-1` or `65536`.

**Comment by dirkschumacher** [comment]
Mmmh. I don't quite know why you want to replace missing values with a value. Wouldn't it make more sense to have let the application decide how to handle missing values?

**Comment by johnjohndoe** [comment]
The application I want to consume the data with is not capable of handling empty cells. Therefore, I would like to import all values and "highlight" empty cells with a custom value. After the import I will remove these values from the database.

**Comment by johnjohndoe** [comment]
I decided not to include this change in the API. Instead all changes specific to the import into [SOS](https://github.com/52North/SOS) will be available on a [separate branch `52north-sos-importer`](https://github.com/johnjohndoe/blume_messnet_api/tree/52north-sos-importer).
